/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GlobalShortcuts {
  /**
   * Creates a portal session and starts listening for Activated/
   * Deactivated signals. `on_event` receives a stream of `ShortcutsEvent`
   * objects; dispatch on the `event` field.
   */
  constructor(onEvent: (arg: ShortcutsEvent) => void)
  /**
   * Replaces the full bound shortcut set. Called on every keybind
   * settings change; semantics match Electron's
   * `globalShortcut.unregisterAll()` + re-register-everything loop.
   */
  bindShortcuts(shortcuts: Array<ShortcutSpec>): void
  /** Shows the portal's native "configure shortcuts" UI for our session. */
  configureShortcuts(): void
  destroy(): void
}

export interface BoundShortcut {
  id: string
  description: string
  triggerDescription: string
}

export declare function getAccentColor(): Promise<number | null>

export declare function requestBackground(autostart: boolean, commandline: Array<string>): Promise<boolean>

/**
 * Discriminated-union event payload delivered to the JS callback passed to
 * `GlobalShortcuts`'s constructor. The `event` field is the discriminant;
 * only the fields relevant to that event are populated. Mirrors the event
 * set PR #1290's C++ `XDPGlobalShortcuts` emitted, so JS-side dispatch can
 * follow the same shape (`switch (payload.event) { ... }`).
 */
export interface ShortcutsEvent {
  event: string
  message?: string
  id?: string
  pressed?: boolean
  timestamp?: number
  shortcuts?: Array<BoundShortcut>
}

export interface ShortcutSpec {
  id: string
  description: string
  preferredTrigger?: string
}

export declare function updateUnityLauncherCount(count: number): Promise<boolean>
